name: myks-setup-action
description: Setup myks
author: The Myks Authors
branding:
  color: green
  icon: download
inputs:
  token:
    description: Github token to use to avoid rate limits
    required: false
    default: ''
  myks:
    description: myks version
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Install myks
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: mykso/myks
        tag: ${{ inputs.myks }}
        token: ${{ inputs.token }}
