---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          release-type: simple
          # The PAT is needed to run required checks on the release PR.
          # If a PR is created with the GITHUB_TOKEN, it will not trigger workflows.
          token: ${{ secrets.MYKSO_BOT_GITHUB_TOKEN }}
